Shared canvas for volmeters
stream-labs/streamlabs-obs pull request #2863
Opened 2020-08-07 22:52 UTC by holiber

Reverts stream-labs/streamlabs-obs#2660

2020-10-02 22:08 UTC, andycreeth commented
I remember there was a bug from last time we reverted this PR that looks like it hasn't been fixed.  If the name of the source overflows onto the next line it overlaps the volmeter:

![image](https://user-images.githubusercontent.com/3180181/94973677-29b72600-04c1-11eb-8f3e-f11032f917ed.png)

2020-10-02 22:54 UTC, holiber commented
Should be fixed now 
![image](https://user-images.githubusercontent.com/3768346/94975773-89b0cb00-04c7-11eb-8931-92699e1b29fc.png)

2020-12-10 20:04 UTC, andycreeth requested changes
Good stuff.  Have a couple minor comments.

2020-12-14 18:14 UTC, holiber commented on app/components/editor/elements/BaseElement.tsx
> +    this.sizeWatcherId = window.setInterval(() => {
I don't think we need to clear it. It's only one 1 interval per app launch.

2020-12-14 21:30 UTC, andycreeth approved these changes

2020-12-14 21:41 UTC, merged