Add IconLibrary Source
stream-labs/streamlabs-obs pull request #3388
Opened 2021-03-18 23:31 UTC by gettinToasty

2021-03-22 20:13 UTC, andycreeth commented on app/components-react/windows/IconLibraryProperties.tsx
> +          setFolderImages(files.map((file: string) => path.join(folder, file)));
Should handle the error case here.  When accessing the filesystem, errors are common and to be expected.

2021-03-22 20:33 UTC, andycreeth requested changes
Looks good!  Just needs the error handling.

2021-03-22 20:33 UTC, andycreeth commented on app/components-react/windows/IconLibraryProperties.tsx
> +    fs.readdir(folder, (err: Error, files: string[]) => {
Same comment regarding handling errors.

2021-04-06 22:23 UTC, holiber approved these changes
Nice

2021-04-06 22:59 UTC, andycreeth approved these changes

2021-04-06 23:01 UTC, merged