Add analytics for the StreamScheduller
stream-labs/streamlabs-obs pull request #3699
Opened 2021-08-17 21:36 UTC by holiber

Should be merged after https://github.com/stream-labs/streamlabs-obs/pull/3686

2021-08-17 21:55 UTC, andycreeth requested changes

2021-08-17 21:55 UTC, andycreeth commented on app/components-react/pages/stream-scheduler/useStreamScheduler.tsx
> +    this.recordFeatureUsage('StreamSchedulerView');
This looks like infinite recursion?

2021-08-18 01:44 UTC, holiber commented on app/components-react/pages/stream-scheduler/useStreamScheduler.tsx
> +    this.recordFeatureUsage('StreamSchedulerView');
good catch

2021-08-18 02:17 UTC, andycreeth approved these changes

2021-08-23 17:58 UTC, andycreeth approved these changes

2021-08-24 17:23 UTC, merged